# Generated by Django 3.2.8 on 2021-11-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('num', models.DecimalField(decimal_places=0, max_digits=5, unique=True)),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '值班成员',
                'verbose_name_plural': '值班成员',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='LegalDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('legal_type', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '法定日期',
                'verbose_name_plural': '法定日期',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('is_workday', models.BooleanField(default=False)),
                ('duty_type', models.IntegerField(default=0)),
                ('staff', models.CharField(blank=True, max_length=10, null=True)),
                ('real_staff', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': '值班安排',
                'verbose_name_plural': '值班安排',
                'ordering': ['-date'],
            },
        ),
    ]
