# Generated by Django 3.2.8 on 2021-11-18 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=50)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('field_key', models.CharField(max_length=50)),
                ('ticket_id', models.IntegerField()),
                ('field_type_id', models.IntegerField()),
                ('char_value', models.CharField(blank=True, default='', max_length=1000)),
                ('int_value', models.IntegerField(blank=True, default=0)),
                ('float_value', models.FloatField(blank=True, default=0.0)),
                ('bool_value', models.BooleanField(blank=True, default=False)),
                ('date_value', models.DateField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0))),
                ('datetime_value', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0))),
                ('time_value', models.TimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0, 1))),
                ('radio_value', models.CharField(blank=True, default='', max_length=50)),
                ('checkbox_value', models.CharField(blank=True, default='', max_length=50)),
                ('select_value', models.CharField(blank=True, default='', max_length=50)),
                ('multi_select_value', models.CharField(blank=True, default='', max_length=50)),
                ('text_value', models.TextField(blank=True, default='')),
                ('username_value', models.CharField(blank=True, default='', max_length=50)),
                ('multi_username_value', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'verbose_name': '工单自定义字段',
                'verbose_name_plural': '工单自定义字段',
            },
        ),
        migrations.CreateModel(
            name='TicketFlowLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=50)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ticket_id', models.IntegerField()),
                ('transition_id', models.IntegerField()),
                ('suggestion', models.CharField(blank=True, default='', max_length=10000)),
                ('participant_type_id', models.IntegerField()),
                ('participant', models.CharField(blank=True, default='', max_length=50)),
                ('state_id', models.IntegerField(blank=True, default=0)),
                ('intervene_type_id', models.IntegerField(default=0)),
                ('ticket_data', models.CharField(blank=True, default='', max_length=10000)),
            ],
            options={
                'verbose_name': '工单流转日志',
                'verbose_name_plural': '工单流转日志',
            },
        ),
        migrations.CreateModel(
            name='TicketRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=50)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('workflow_id', models.IntegerField()),
                ('sn', models.CharField(max_length=25)),
                ('state_id', models.IntegerField()),
                ('parent_ticket_id', models.IntegerField(default=0)),
                ('parent_ticket_state_id', models.IntegerField(default=0)),
                ('participant_type_id', models.IntegerField(default=0)),
                ('participant', models.CharField(blank=True, default='', max_length=1000)),
                ('relation', models.CharField(blank=True, default='', max_length=1000)),
                ('in_add_node', models.BooleanField(default=False)),
                ('add_node_man', models.CharField(blank=True, default='', max_length=50)),
                ('script_run_last_result', models.BooleanField(default=True)),
                ('act_state_id', models.IntegerField(default=1)),
                ('multi_all_person', models.CharField(blank=True, default='{}', max_length=1000)),
            ],
            options={
                'verbose_name': '工单记录',
                'verbose_name_plural': '工单记录',
            },
        ),
        migrations.CreateModel(
            name='TicketUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=50)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100)),
                ('in_process', models.BooleanField(default=False)),
                ('worked', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticketrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
