# Generated by Django 3.2.8 on 2021-11-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoonDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('parent_dept_id', models.IntegerField(blank=True, default=0)),
                ('leader', models.CharField(blank=True, default='', max_length=50)),
                ('approver', models.CharField(blank=True, default='', max_length=100)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='LoonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('label', models.CharField(blank=True, default='{}', max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='LoonUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=50)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
            },
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('alias', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(default='', max_length=13)),
                ('dept_id', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_workflow_admin', models.BooleanField(default=False)),
                ('creator', models.CharField(max_length=50)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
